# Data Processing

In [1]:
# Calling Libraries

import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report

In [2]:
# Downlouding dataset

df=pd.read_csv("corporate_stress_dataset.csv")

/var/folders/kx/n6bh82zd3w5_blhwkxh6d2440000gn/T/ipykernel_2149/991037034.py:3: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("corporate_stress_dataset.csv")

In [3]:
print(df.head(3)) # datasetni boshidan 3 ta rows ni ekranga chiqarish

print(df.tail(3))# oxiridan 3 ta

   ID  Age      Gender Marital_Status   Job_Role  Experience_Years  \
0   1   56  Non-Binary        Widowed  Developer                 5
1   2   46      Female         Single    Analyst                20
2   3   32      Female         Single  Developer                10

   Monthly_Salary_INR  Working_Hours_per_Week  Commute_Time_Hours  \
0           102703.08                      44                1.72
1           165583.91                      54                0.62
2            38005.39                      81                1.22

   Remote_Work  ...  Work_Life_Balance Family_Support_Level Job_Satisfaction  \
0         True  ...                9.0                    2                5
1         True  ...                9.0                    1               10
2        False  ...                6.0                    1                1

  Performance_Rating  Team_Size  Training_Opportunities  \
0               10.0         38                   False
1                9.0         72                    True
2                1.0         67                   False

  Gender_Bias_Experienced  Discrimination_Experienced  Burnout_Symptoms  \
0                    True                        True                No
1                    True                        True                No
2                   False                       False               Yes

   Location
0    Tier-3
1    Tier-3
2     Metro

[3 rows x 30 columns]
          ID  Age  Gender Marital_Status Job_Role  Experience_Years  \
49997  49998   43  Female       Divorced  Manager                 7
49998  49999   62    Male        Married       HR                 9
49999  50000   19  Female       Divorced  Manager                 0

       Monthly_Salary_INR  Working_Hours_per_Week  Commute_Time_Hours  \
49997           109814.51                      49                1.49
49998            74918.42                      72                2.64
49999            31783.31                      50                2.52

       Remote_Work  ...  Work_Life_Balance Family_Support_Level  \
49997         True  ...                0.0                    0
49998        False  ...               10.0                    4
49999         True  ...               10.0                    6

      Job_Satisfaction Performance_Rating  Team_Size  Training_Opportunities  \
49997               10                6.0         56                   False
49998                2                8.0         50                    True
49999                6                1.0         50                    True

      Gender_Bias_Experienced  Discrimination_Experienced  Burnout_Symptoms  \
49997                    True                       False                No
49998                   False                        True               Yes
49999                    True                       False                No

       Location
49997     Metro
49998    Tier-2
49999    Tier-1

[3 rows x 30 columns]

In [4]:
df.head(1)

,ID,Age,Gender,Marital_Status,Job_Role,Experience_Years,Monthly_Salary_INR,Working_Hours_per_Week,Commute_Time_Hours,Remote_Work,...,Work_Life_Balance,Family_Support_Level,Job_Satisfaction,Performance_Rating,Team_Size,Training_Opportunities,Gender_Bias_Experienced,Discrimination_Experienced,Burnout_Symptoms,Location
0,1,56,Non-Binary,Widowed,Developer,5,102703.08,44,1.72,True,...,9.0,2,5,10.0,38,False,True,True,No,Tier-3

In [5]:
# Dataset haqida umumiy ma'lumot

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 30 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID                                50000 non-null  int64
 1   Age                               50000 non-null  int64
 2   Gender                            50000 non-null  object
 3   Marital_Status                    50000 non-null  object
 4   Job_Role                          49999 non-null  object
 5   Experience_Years                  50000 non-null  int64
 6   Monthly_Salary_INR                50000 non-null  float64
 7   Working_Hours_per_Week            50000 non-null  int64
 8   Commute_Time_Hours                49999 non-null  float64
 9   Remote_Work                       50000 non-null  bool
 10  Stress_Level                      49999 non-null  float64
 11  Health_Issues                     37459 non-null  object
 12  Company_Size                      50000 non-null  object
 13  Department                        50000 non-null  object
 14  Sleep_Hours                       50000 non-null  float64
 15  Physical_Activity_Hours_per_Week  50000 non-null  float64
 16  Mental_Health_Leave_Taken         49999 non-null  object
 17  Manager_Support_Level             50000 non-null  int64
 18  Work_Pressure_Level               49999 non-null  float64
 19  Annual_Leaves_Taken               49999 non-null  float64
 20  Work_Life_Balance                 49998 non-null  float64
 21  Family_Support_Level              50000 non-null  int64
 22  Job_Satisfaction                  50000 non-null  int64
 23  Performance_Rating                49999 non-null  float64
 24  Team_Size                         50000 non-null  int64
 25  Training_Opportunities            50000 non-null  bool
 26  Gender_Bias_Experienced           50000 non-null  bool
 27  Discrimination_Experienced        50000 non-null  bool
 28  Burnout_Symptoms                  50000 non-null  object
 29  Location                          50000 non-null  object
dtypes: bool(4), float64(9), int64(8), object(9)
memory usage: 10.1+ MB

In [6]:
# Selecting Categoricol and Numerical Columns

categorical_col=df.select_dtypes(include=["object","category"]).columns.tolist()
print(f"CATEGORICAL COLUMNS:\n{categorical_col}")
print(f"TOTAL NUMBER OF CATEGORICAL COLUMNS: {len(categorical_col)}") # object tipli ustunlarni umumiy soni

numerical_col=df.select_dtypes(include=["int64","float64"]).columns.tolist()
print(f"\nNUMERICAL COLUMNS:{numerical_col}")
print(f"TOTAL NUMBER OF NUMERICAL COLUMNS:{len(numerical_col)}") # int va float tipidagi ustunlarni umumiy soni

CATEGORICAL COLUMNS:
['Gender', 'Marital_Status', 'Job_Role', 'Health_Issues', 'Company_Size', 'Department', 'Mental_Health_Leave_Taken', 'Burnout_Symptoms', 'Location']
TOTAL NUMBER OF CATEGORICAL COLUMNS: 9

NUMERICAL COLUMNS:['ID', 'Age', 'Experience_Years', 'Monthly_Salary_INR', 'Working_Hours_per_Week', 'Commute_Time_Hours', 'Stress_Level', 'Sleep_Hours', 'Physical_Activity_Hours_per_Week', 'Manager_Support_Level', 'Work_Pressure_Level', 'Annual_Leaves_Taken', 'Work_Life_Balance', 'Family_Support_Level', 'Job_Satisfaction', 'Performance_Rating', 'Team_Size']
TOTAL NUMBER OF NUMERICAL COLUMNS:17

# Handling with Missing values

In [7]:
# Finding Missing values

missing_columns=df.isnull().sum()
missing_columns=missing_columns[missing_columns>0]

if not missing_columns.empty:
    print((f"MISSING VALUES:\n{missing_columns}"))
else:
    print("No missining values")

MISSING VALUES:
Job_Role                         1
Commute_Time_Hours               1
Stress_Level                     1
Health_Issues                12541
Mental_Health_Leave_Taken        1
Work_Pressure_Level              1
Annual_Leaves_Taken              1
Work_Life_Balance                2
Performance_Rating               1
dtype: int64

In [8]:
# Missing values larni umumiy formula bilan to'ldirib ketish

missing_columns=df.columns[df.isnull().sum()>0]

for col in missing_columns:
    if df[col].dtype=="object": 
        df[col].fillna(df[col].mode()[0],inplace=True) # object tipidagi NaN qiymatlarni mode()(eng ko'p uchragan qiymatni tanlab olish) funksiyasi yordamida to'ldirish buyrug'i
    else:
        df[col].fillna(df[col].mean(),inplace=True) # int va float tipidagilarni mean()( o'rtacha qiymat) funfsiyasi bilan to'ldirish

/var/folders/kx/n6bh82zd3w5_blhwkxh6d2440000gn/T/ipykernel_2149/3353403899.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True) # object tipidagi NaN qiymatlarni mode()(eng ko'p uchragan qiymatni tanlab olish) funksiyasi yordamida to'ldirish buyrug'i
/var/folders/kx/n6bh82zd3w5_blhwkxh6d2440000gn/T/ipykernel_2149/3353403899.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(),inplace=True) # int va float tipidagilarni mean()( o'rtacha qiymat) funfsiyasi bilan to'ldirish

In [9]:
# Missing values larni qaytadan tekshiramiz

missing_columns=df.isnull().sum()
missing_columns=missing_columns[missing_columns>0]

if not missing_columns.empty:
    print((f"MISSING VALUES:\n{missing_columns}"))
else:
    print("No missining values")

No missining values

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 30 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID                                50000 non-null  int64
 1   Age                               50000 non-null  int64
 2   Gender                            50000 non-null  object
 3   Marital_Status                    50000 non-null  object
 4   Job_Role                          50000 non-null  object
 5   Experience_Years                  50000 non-null  int64
 6   Monthly_Salary_INR                50000 non-null  float64
 7   Working_Hours_per_Week            50000 non-null  int64
 8   Commute_Time_Hours                50000 non-null  float64
 9   Remote_Work                       50000 non-null  bool
 10  Stress_Level                      50000 non-null  float64
 11  Health_Issues                     50000 non-null  object
 12  Company_Size                      50000 non-null  object
 13  Department                        50000 non-null  object
 14  Sleep_Hours                       50000 non-null  float64
 15  Physical_Activity_Hours_per_Week  50000 non-null  float64
 16  Mental_Health_Leave_Taken         50000 non-null  object
 17  Manager_Support_Level             50000 non-null  int64
 18  Work_Pressure_Level               50000 non-null  float64
 19  Annual_Leaves_Taken               50000 non-null  float64
 20  Work_Life_Balance                 50000 non-null  float64
 21  Family_Support_Level              50000 non-null  int64
 22  Job_Satisfaction                  50000 non-null  int64
 23  Performance_Rating                50000 non-null  float64
 24  Team_Size                         50000 non-null  int64
 25  Training_Opportunities            50000 non-null  bool
 26  Gender_Bias_Experienced           50000 non-null  bool
 27  Discrimination_Experienced        50000 non-null  bool
 28  Burnout_Symptoms                  50000 non-null  object
 29  Location                          50000 non-null  object
dtypes: bool(4), float64(9), int64(8), object(9)
memory usage: 10.1+ MB

In [11]:
df["Burnout_Symptoms"].value_counts()

Burnout_Symptoms
Occasional    16676
No            16662
Yes           16661
3                 1
Name: count, dtype: int64

In [12]:
#Mapping

df["Burnout_Symptoms_binary"]=df["Burnout_Symptoms"].map({
    "Occasional":0,
    "No":1,
    "3":1,
    "Yes":2
})

In [13]:
df.drop("Burnout_Symptoms",axis=1,inplace=True) # Eski ustunni tashlab yubordik

In [13]:
df["Burnout_Symptoms_binary"]

0        1
1        1
2        2
3        2
4        1
        ..
49995    1
49996    0
49997    1
49998    2
49999    1
Name: Burnout_Symptoms_binary, Length: 50000, dtype: int64

In [14]:
categorical_col=df.select_dtypes(include=["object","category"]).columns.tolist()
print(f"CATEGORICAL COLUMNS:\n{categorical_col}")
print(f"TOTAL NUMBER OF CATEGORICAL COLUMNS: {len(categorical_col)}") # object tipli ustunlarni umumiy soni

numerical_col=df.select_dtypes(include=["int64","float64"]).columns.tolist()
print(f"\nNUMERICAL COLUMNS:{numerical_col}")
print(f"TOTAL NUMBER OF NUMERICAL COLUMNS:{len(numerical_col)}") # int va float tipidagi ustunlarni umumiy soni

CATEGORICAL COLUMNS:
['Gender', 'Marital_Status', 'Job_Role', 'Health_Issues', 'Company_Size', 'Department', 'Mental_Health_Leave_Taken', 'Burnout_Symptoms', 'Location']
TOTAL NUMBER OF CATEGORICAL COLUMNS: 9

NUMERICAL COLUMNS:['ID', 'Age', 'Experience_Years', 'Monthly_Salary_INR', 'Working_Hours_per_Week', 'Commute_Time_Hours', 'Stress_Level', 'Sleep_Hours', 'Physical_Activity_Hours_per_Week', 'Manager_Support_Level', 'Work_Pressure_Level', 'Annual_Leaves_Taken', 'Work_Life_Balance', 'Family_Support_Level', 'Job_Satisfaction', 'Performance_Rating', 'Team_Size', 'Burnout_Symptoms_binary']
TOTAL NUMBER OF NUMERICAL COLUMNS:18

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 31 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID                                50000 non-null  int64
 1   Age                               50000 non-null  int64
 2   Gender                            50000 non-null  object
 3   Marital_Status                    50000 non-null  object
 4   Job_Role                          50000 non-null  object
 5   Experience_Years                  50000 non-null  int64
 6   Monthly_Salary_INR                50000 non-null  float64
 7   Working_Hours_per_Week            50000 non-null  int64
 8   Commute_Time_Hours                50000 non-null  float64
 9   Remote_Work                       50000 non-null  bool
 10  Stress_Level                      50000 non-null  float64
 11  Health_Issues                     50000 non-null  object
 12  Company_Size                      50000 non-null  object
 13  Department                        50000 non-null  object
 14  Sleep_Hours                       50000 non-null  float64
 15  Physical_Activity_Hours_per_Week  50000 non-null  float64
 16  Mental_Health_Leave_Taken         50000 non-null  object
 17  Manager_Support_Level             50000 non-null  int64
 18  Work_Pressure_Level               50000 non-null  float64
 19  Annual_Leaves_Taken               50000 non-null  float64
 20  Work_Life_Balance                 50000 non-null  float64
 21  Family_Support_Level              50000 non-null  int64
 22  Job_Satisfaction                  50000 non-null  int64
 23  Performance_Rating                50000 non-null  float64
 24  Team_Size                         50000 non-null  int64
 25  Training_Opportunities            50000 non-null  bool
 26  Gender_Bias_Experienced           50000 non-null  bool
 27  Discrimination_Experienced        50000 non-null  bool
 28  Burnout_Symptoms                  50000 non-null  object
 29  Location                          50000 non-null  object
 30  Burnout_Symptoms_binary           50000 non-null  int64
dtypes: bool(4), float64(9), int64(9), object(9)
memory usage: 10.5+ MB

# Encoding (from categorical to numerical)

In [16]:
# Finding cardinality

cardinality=df[categorical_col].nunique()
print(cardinality)

Gender                       3
Marital_Status               4
Job_Role                     6
Health_Issues                3
Company_Size                 3
Department                   6
Mental_Health_Leave_Taken    6
Burnout_Symptoms             4
Location                     4
dtype: int64

In [17]:
# Encoding (One_hot encoding) 
# with get_dummies ( cardinality o'rtacha 5 atrofida chiqqani (cardinality low) uchun)

one_hot_encoding=pd.get_dummies(df,columns=categorical_col,drop_first=True) # pandas kutubxonasi yordamida one-hot encoding turidan foydalandim
one_hot_encoding

,ID,Age,Experience_Years,Monthly_Salary_INR,Working_Hours_per_Week,Commute_Time_Hours,Remote_Work,Stress_Level,Sleep_Hours,Physical_Activity_Hours_per_Week,...,Mental_Health_Leave_Taken_0,Mental_Health_Leave_Taken_1,Mental_Health_Leave_Taken_FALSE,Mental_Health_Leave_Taken_TRUE,Burnout_Symptoms_No,Burnout_Symptoms_Occasional,Burnout_Symptoms_Yes,Location_Tier-1,Location_Tier-2,Location_Tier-3
0,1,56,5,102703.08,44,1.72,True,0.0,5.6,1.9,...,False,False,True,False,True,False,False,False,False,True
1,2,46,20,165583.91,54,0.62,True,7.0,9.0,3.5,...,False,False,False,True,True,False,False,False,False,True
2,3,32,10,38005.39,81,1.22,False,7.0,7.9,8.4,...,False,False,True,False,False,False,True,False,False,False
3,4,60,26,51127.36,79,2.03,False,6.0,4.1,6.4,...,False,False,False,True,False,False,True,False,False,False
4,5,25,29,174597.45,63,1.45,True,8.0,4.0,9.2,...,False,False,False,True,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,43,8,34594.10,58,1.66,False,0.0,7.5,4.0,...,False,False,False,False,True,False,False,False,False,True
49996,49997,45,31,117925.92,42,1.58,False,1.0,4.5,0.1,...,False,False,False,False,False,True,False,False,True,False
49997,49998,43,7,109814.51,49,1.49,True,6.0,7.8,5.4,...,False,False,False,False,True,False,False,False,False,False
49998,49999,62,9,74918.42,72,2.64,False,4.0,5.6,7.1,...,False,False,False,False,False,False,True,False,True,False
49999,50000,19,0,31783.31,50,2.52,True,9.0,4.5,2.7,...,False,False,False,False,True,False,False,True,False,False

In [18]:
df=one_hot_encoding
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 52 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID                                50000 non-null  int64
 1   Age                               50000 non-null  int64
 2   Experience_Years                  50000 non-null  int64
 3   Monthly_Salary_INR                50000 non-null  float64
 4   Working_Hours_per_Week            50000 non-null  int64
 5   Commute_Time_Hours                50000 non-null  float64
 6   Remote_Work                       50000 non-null  bool
 7   Stress_Level                      50000 non-null  float64
 8   Sleep_Hours                       50000 non-null  float64
 9   Physical_Activity_Hours_per_Week  50000 non-null  float64
 10  Manager_Support_Level             50000 non-null  int64
 11  Work_Pressure_Level               50000 non-null  float64
 12  Annual_Leaves_Taken               50000 non-null  float64
 13  Work_Life_Balance                 50000 non-null  float64
 14  Family_Support_Level              50000 non-null  int64
 15  Job_Satisfaction                  50000 non-null  int64
 16  Performance_Rating                50000 non-null  float64
 17  Team_Size                         50000 non-null  int64
 18  Training_Opportunities            50000 non-null  bool
 19  Gender_Bias_Experienced           50000 non-null  bool
 20  Discrimination_Experienced        50000 non-null  bool
 21  Burnout_Symptoms_binary           50000 non-null  int64
 22  Gender_Male                       50000 non-null  bool
 23  Gender_Non-Binary                 50000 non-null  bool
 24  Marital_Status_Married            50000 non-null  bool
 25  Marital_Status_Single             50000 non-null  bool
 26  Marital_Status_Widowed            50000 non-null  bool
 27  Job_Role_Developer                50000 non-null  bool
 28  Job_Role_HR                       50000 non-null  bool
 29  Job_Role_Manager                  50000 non-null  bool
 30  Job_Role_Sales                    50000 non-null  bool
 31  Job_Role_Support                  50000 non-null  bool
 32  Health_Issues_Mental              50000 non-null  bool
 33  Health_Issues_Physical            50000 non-null  bool
 34  Company_Size_Medium               50000 non-null  bool
 35  Company_Size_Small                50000 non-null  bool
 36  Department_Finance                50000 non-null  bool
 37  Department_HR                     50000 non-null  bool
 38  Department_IT                     50000 non-null  bool
 39  Department_Marketing              50000 non-null  bool
 40  Department_Sales                  50000 non-null  bool
 41  Mental_Health_Leave_Taken_True    50000 non-null  bool
 42  Mental_Health_Leave_Taken_0       50000 non-null  bool
 43  Mental_Health_Leave_Taken_1       50000 non-null  bool
 44  Mental_Health_Leave_Taken_FALSE   50000 non-null  bool
 45  Mental_Health_Leave_Taken_TRUE    50000 non-null  bool
 46  Burnout_Symptoms_No               50000 non-null  bool
 47  Burnout_Symptoms_Occasional       50000 non-null  bool
 48  Burnout_Symptoms_Yes              50000 non-null  bool
 49  Location_Tier-1                   50000 non-null  bool
 50  Location_Tier-2                   50000 non-null  bool
 51  Location_Tier-3                   50000 non-null  bool
dtypes: bool(34), float64(9), int64(9)
memory usage: 8.5 MB

In [19]:
df[df.columns]=df[df.columns].astype(int) # Qo'shilgan yangi ustunlarni booleandan int ga o'tkazish
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 52 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID                                50000 non-null  int64
 1   Age                               50000 non-null  int64
 2   Experience_Years                  50000 non-null  int64
 3   Monthly_Salary_INR                50000 non-null  int64
 4   Working_Hours_per_Week            50000 non-null  int64
 5   Commute_Time_Hours                50000 non-null  int64
 6   Remote_Work                       50000 non-null  int64
 7   Stress_Level                      50000 non-null  int64
 8   Sleep_Hours                       50000 non-null  int64
 9   Physical_Activity_Hours_per_Week  50000 non-null  int64
 10  Manager_Support_Level             50000 non-null  int64
 11  Work_Pressure_Level               50000 non-null  int64
 12  Annual_Leaves_Taken               50000 non-null  int64
 13  Work_Life_Balance                 50000 non-null  int64
 14  Family_Support_Level              50000 non-null  int64
 15  Job_Satisfaction                  50000 non-null  int64
 16  Performance_Rating                50000 non-null  int64
 17  Team_Size                         50000 non-null  int64
 18  Training_Opportunities            50000 non-null  int64
 19  Gender_Bias_Experienced           50000 non-null  int64
 20  Discrimination_Experienced        50000 non-null  int64
 21  Burnout_Symptoms_binary           50000 non-null  int64
 22  Gender_Male                       50000 non-null  int64
 23  Gender_Non-Binary                 50000 non-null  int64
 24  Marital_Status_Married            50000 non-null  int64
 25  Marital_Status_Single             50000 non-null  int64
 26  Marital_Status_Widowed            50000 non-null  int64
 27  Job_Role_Developer                50000 non-null  int64
 28  Job_Role_HR                       50000 non-null  int64
 29  Job_Role_Manager                  50000 non-null  int64
 30  Job_Role_Sales                    50000 non-null  int64
 31  Job_Role_Support                  50000 non-null  int64
 32  Health_Issues_Mental              50000 non-null  int64
 33  Health_Issues_Physical            50000 non-null  int64
 34  Company_Size_Medium               50000 non-null  int64
 35  Company_Size_Small                50000 non-null  int64
 36  Department_Finance                50000 non-null  int64
 37  Department_HR                     50000 non-null  int64
 38  Department_IT                     50000 non-null  int64
 39  Department_Marketing              50000 non-null  int64
 40  Department_Sales                  50000 non-null  int64
 41  Mental_Health_Leave_Taken_True    50000 non-null  int64
 42  Mental_Health_Leave_Taken_0       50000 non-null  int64
 43  Mental_Health_Leave_Taken_1       50000 non-null  int64
 44  Mental_Health_Leave_Taken_FALSE   50000 non-null  int64
 45  Mental_Health_Leave_Taken_TRUE    50000 non-null  int64
 46  Burnout_Symptoms_No               50000 non-null  int64
 47  Burnout_Symptoms_Occasional       50000 non-null  int64
 48  Burnout_Symptoms_Yes              50000 non-null  int64
 49  Location_Tier-1                   50000 non-null  int64
 50  Location_Tier-2                   50000 non-null  int64
 51  Location_Tier-3                   50000 non-null  int64
dtypes: int64(52)
memory usage: 19.8 MB

In [20]:
categorical_col=df.select_dtypes(include=["object","category"]).columns.tolist()
print(f"CATEGORICAL COLUMNS:\n{categorical_col}")
print(f"TOTAL NUMBER OF CATEGORICAL COLUMNS: {len(categorical_col)}")

CATEGORICAL COLUMNS:
[]
TOTAL NUMBER OF CATEGORICAL COLUMNS: 0

# Scaling

In [22]:
# scaling (MinMax scaler)

min_max_scaling=MinMaxScaler()
df_scaled=pd.DataFrame(min_max_scaling.fit_transform(df),columns=df.columns) 
df_scaled

,ID,Age,Experience_Years,Monthly_Salary_INR,Working_Hours_per_Week,Commute_Time_Hours,Remote_Work,Stress_Level,Sleep_Hours,Physical_Activity_Hours_per_Week,...,Department_Marketing,Department_Sales,Mental_Health_Leave_Taken_True,Mental_Health_Leave_Taken_0,Mental_Health_Leave_Taken_1,Mental_Health_Leave_Taken_FALSE,Mental_Health_Leave_Taken_TRUE,Location_Tier-1,Location_Tier-2,Location_Tier-3
0,0.00000,0.808511,0.125,0.459479,0.163636,0.333333,1.0,0.0,0.2,0.1,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.00002,0.595745,0.500,0.808829,0.345455,0.000000,1.0,0.7,1.0,0.3,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,0.00004,0.297872,0.250,0.100027,0.836364,0.333333,0.0,0.7,0.6,0.8,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.00006,0.893617,0.650,0.172931,0.800000,0.666667,0.0,0.6,0.0,0.6,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.00008,0.148936,0.725,0.858910,0.509091,0.333333,1.0,0.8,0.0,0.9,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,0.99992,0.531915,0.200,0.081076,0.418182,0.333333,0.0,0.0,0.6,0.4,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
49996,0.99994,0.574468,0.775,0.544049,0.127273,0.333333,0.0,0.1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
49997,0.99996,0.531915,0.175,0.498986,0.254545,0.333333,1.0,0.6,0.6,0.5,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49998,0.99998,0.936170,0.225,0.305110,0.672727,0.666667,0.0,0.4,0.2,0.7,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
49999,1.00000,0.021277,0.000,0.065459,0.272727,0.666667,1.0,0.9,0.0,0.2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [23]:
df=df_scaled

In [24]:
df.head()

,ID,Age,Experience_Years,Monthly_Salary_INR,Working_Hours_per_Week,Commute_Time_Hours,Remote_Work,Stress_Level,Sleep_Hours,Physical_Activity_Hours_per_Week,...,Department_Marketing,Department_Sales,Mental_Health_Leave_Taken_True,Mental_Health_Leave_Taken_0,Mental_Health_Leave_Taken_1,Mental_Health_Leave_Taken_FALSE,Mental_Health_Leave_Taken_TRUE,Location_Tier-1,Location_Tier-2,Location_Tier-3
0,0.00000,0.808511,0.125,0.459479,0.163636,0.333333,1.0,0.0,0.2,0.1,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.00002,0.595745,0.500,0.808829,0.345455,0.000000,1.0,0.7,1.0,0.3,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,0.00004,0.297872,0.250,0.100027,0.836364,0.333333,0.0,0.7,0.6,0.8,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.00006,0.893617,0.650,0.172931,0.800000,0.666667,0.0,0.6,0.0,0.6,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.00008,0.148936,0.725,0.858910,0.509091,0.333333,1.0,0.8,0.0,0.9,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 49 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID                                50000 non-null  float64
 1   Age                               50000 non-null  float64
 2   Experience_Years                  50000 non-null  float64
 3   Monthly_Salary_INR                50000 non-null  float64
 4   Working_Hours_per_Week            50000 non-null  float64
 5   Commute_Time_Hours                50000 non-null  float64
 6   Remote_Work                       50000 non-null  float64
 7   Stress_Level                      50000 non-null  float64
 8   Sleep_Hours                       50000 non-null  float64
 9   Physical_Activity_Hours_per_Week  50000 non-null  float64
 10  Manager_Support_Level             50000 non-null  float64
 11  Work_Pressure_Level               50000 non-null  float64
 12  Annual_Leaves_Taken               50000 non-null  float64
 13  Work_Life_Balance                 50000 non-null  float64
 14  Family_Support_Level              50000 non-null  float64
 15  Job_Satisfaction                  50000 non-null  float64
 16  Performance_Rating                50000 non-null  float64
 17  Team_Size                         50000 non-null  float64
 18  Training_Opportunities            50000 non-null  float64
 19  Gender_Bias_Experienced           50000 non-null  float64
 20  Discrimination_Experienced        50000 non-null  float64
 21  Burnout_Symptoms_binary           50000 non-null  float64
 22  Gender_Male                       50000 non-null  float64
 23  Gender_Non-Binary                 50000 non-null  float64
 24  Marital_Status_Married            50000 non-null  float64
 25  Marital_Status_Single             50000 non-null  float64
 26  Marital_Status_Widowed            50000 non-null  float64
 27  Job_Role_Developer                50000 non-null  float64
 28  Job_Role_HR                       50000 non-null  float64
 29  Job_Role_Manager                  50000 non-null  float64
 30  Job_Role_Sales                    50000 non-null  float64
 31  Job_Role_Support                  50000 non-null  float64
 32  Health_Issues_Mental              50000 non-null  float64
 33  Health_Issues_Physical            50000 non-null  float64
 34  Company_Size_Medium               50000 non-null  float64
 35  Company_Size_Small                50000 non-null  float64
 36  Department_Finance                50000 non-null  float64
 37  Department_HR                     50000 non-null  float64
 38  Department_IT                     50000 non-null  float64
 39  Department_Marketing              50000 non-null  float64
 40  Department_Sales                  50000 non-null  float64
 41  Mental_Health_Leave_Taken_True    50000 non-null  float64
 42  Mental_Health_Leave_Taken_0       50000 non-null  float64
 43  Mental_Health_Leave_Taken_1       50000 non-null  float64
 44  Mental_Health_Leave_Taken_FALSE   50000 non-null  float64
 45  Mental_Health_Leave_Taken_TRUE    50000 non-null  float64
 46  Location_Tier-1                   50000 non-null  float64
 47  Location_Tier-2                   50000 non-null  float64
 48  Location_Tier-3                   50000 non-null  float64
dtypes: float64(49)
memory usage: 18.7 MB

# Training Process

In [21]:
# Selecting Target(Output) and Features(Input)

x=df.drop("Burnout_Symptoms_binary",axis=1) # Features (Input)
y=df["Burnout_Symptoms_binary"] # target (Output)

In [22]:
y.head()

0    1
1    1
2    2
3    2
4    1
Name: Burnout_Symptoms_binary, dtype: int64

In [23]:
x.head()

,ID,Age,Experience_Years,Monthly_Salary_INR,Working_Hours_per_Week,Commute_Time_Hours,Remote_Work,Stress_Level,Sleep_Hours,Physical_Activity_Hours_per_Week,...,Mental_Health_Leave_Taken_0,Mental_Health_Leave_Taken_1,Mental_Health_Leave_Taken_FALSE,Mental_Health_Leave_Taken_TRUE,Burnout_Symptoms_No,Burnout_Symptoms_Occasional,Burnout_Symptoms_Yes,Location_Tier-1,Location_Tier-2,Location_Tier-3
0,1,56,5,102703,44,1,1,0,5,1,...,0,0,1,0,1,0,0,0,0,1
1,2,46,20,165583,54,0,1,7,9,3,...,0,0,0,1,1,0,0,0,0,1
2,3,32,10,38005,81,1,0,7,7,8,...,0,0,1,0,0,0,1,0,0,0
3,4,60,26,51127,79,2,0,6,4,6,...,0,0,0,1,0,0,1,0,0,0
4,5,25,29,174597,63,1,1,8,4,9,...,0,0,0,1,1,0,0,1,0,0

In [24]:
# Data splitting

x_train,x_temp,y_train,y_temp=train_test_split(x,y, test_size=0.3, random_state=42) # 70 % datasetni traing uchun belgiladik 

x_test, x_val, y_test, y_val=train_test_split(x_temp,y_temp, test_size=0.5, random_state=42) # 30% datasetdan 15 % ini validating uchun qolgan 15 foizi testing uchun

In [25]:
print(x_train.shape)
print(x_val.shape)
print(x_test.shape)

print(y_test.shape)
print(y_val.shape)

(35000, 51)
(7500, 51)
(7500, 51)
(7500,)
(7500,)

In [26]:
y_train[:10]

38094    0
40624    0
49425    1
35734    2
41708    0
31176    2
34748    2
24360    0
41276    1
28248    2
Name: Burnout_Symptoms_binary, dtype: int64

In [27]:
model=LogisticRegression(multi_class="multinomial",solver="lbfgs",max_iter=200) # selecting model

model.fit(x_train,y_train) # teaching model

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=200, multi_class='multinomial')

In [28]:
y.head() # old features

0    1
1    1
2    2
3    2
4    1
Name: Burnout_Symptoms_binary, dtype: int64

In [29]:
y_pred=model.predict(x_test)# predicting 
print(f"Predict columns:\n{y_pred[:5]}")

Predict columns:
[1 0 2 2 1]

In [34]:
# Accurary score

accuracy=accuracy_score(y_test,y_pred)
print(f"Accurary:{accuracy*100:.2f}%")

Accurary:76.16%

In [35]:
# Classification report (Prediction,Recall,F1-score)
print("Classification Report:")
print(classification_report(y_test,y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.73      0.77      2473
           1       0.69      0.72      0.70      2511
           2       0.79      0.84      0.81      2516

    accuracy                           0.76      7500
   macro avg       0.76      0.76      0.76      7500
weighted avg       0.76      0.76      0.76      7500